### ISSUE TITLE
Error: sox FAIL formats: no handler for file extension `mp3'

### ISSUE THREAD

**Issue by arshaplus** [maximal/audio-waveform-php#3]
hey all, this error happend for me on use this code: 

`$waveform = new Waveform('storage/'.$Track->file_320);`
`Waveform::$color = [255, 0, 0, 0.5];`
`Waveform::$backgroundColor = [0, 0, 0, 0];`
`$success = $waveform->getWaveform('storage/'.$WaveFormImage, 1024, 512);`

how fix it ?

**Comment by maximal** [comment]
Hi there.

You should install SoX handlers for various audio formats as it stated in `readme.md`.

```sh
# SoX itself
sudo apt install sox
# Format handlers
sudo apt install libsox-fmt-all
# PHP image graphic library
sudo apt install php-gd
```
