### ISSUE TITLE
Return value of getWaveform function

### ISSUE THREAD

**Issue by ghost** [maximal/audio-waveform-php#5]
I tried your package, but when i used the function in the title, I get a boolean (true) instead of the image I expected to get. The getWaveformData function on the other hand return the expected waveform data. I used Version 1.2.0 of the library.

I used PHP 7.2.15 and the GD-Extension is enabled.

**Comment by maximal** [comment]
See the readme file and the PhpDoc for `getWaveform()` method:

```php
/**
 * Get waveform from the audio file.
 * @param string $filename Image file name
 * @param int $width Width of the image file in pixels
 * @param int $height Height of the image file in pixels
 * @param bool $onePhase `true` to get positive values only, `false` to get both phases
 * @return bool Returns `true` on success or `false` on failure.
 * @throws \Exception
 */
```

`getWaveform()` saves the image to `$filename` and returns boolean (whether the operation succeded).
